language: python
sudo: false
install: pip install -r requirements.txt

matrix:
    include:
        # Python 3.5
        - python: 3.5
          env: TOX_ENV=py35

        # Python 3.6
        - python: 3.6
          env: TOX_ENV=py36
        - python: 3.6
          env: TOX_ENV=docs

script:
  - tox -e "${TOX_ENV}"

before_install:
  - pip install codecov

after_success:
  - coverage combine
  - codecov

notifications:
  email:
    - gledesma@gmail.com
